- taskqueue/gcloud/aio/taskqueue/taskqueue.py
Allows users to capture processing time information when using the LocalTaskQueue emulation layer.
> feat(taskqueue): add perf-timing hookins to LocalTaskQueue

- storage/gcloud/aio/storage/storage.py
This file hadn't been touched in forever, so I included a bunch of cleanup here. The functional changes are `Storage.list_objects` and `Bucket.list_blobs`, which can be used with an optional prefix to list all objects in a given bucket and/or in a given folder in a bucket.
> feat(storage): implement "list blobs" feature

- storage/gcloud/aio/storage/storage.py
- storage/tests/integration/smoke_test.py
~~I'll continue to retry circle tests to make sure this is passing~~
Edit: Circle tests passing
> feature(delete): add ability to delete specific object

- storage/gcloud/aio/storage/storage.py
- storage/tests/integration/upload_resumable_test.py
Memory efficient upload method first provided by @JensMadsen in #48.
> feat(storage): upload via streams

- datastore/gcloud/aio/datastore/value.py
- datastore/tests/unit/value_test.py
Also added the missing test for it
> Put supported types in a method so it's updated when key_kind is updated

- storage/gcloud/aio/storage/blob.py
- storage/gcloud/aio/storage/bucket.py
- storage/tests/integration/conftest.py
- storage/tests/integration/signed_url_test.py
Create utility function on GCS Blob for a signed url for non-logged in access to the GCS blob.
> Storage signed url

- datastore/gcloud/aio/datastore/constants.py
- datastore/gcloud/aio/datastore/entity.py
- datastore/gcloud/aio/datastore/value.py
See https://cloud.google.com/datastore/docs/concepts/entities#embedded_entity
> Add support for embedded entity values

- storage/README.rst
I have added a simple example to Readme.
With respect to the issue #84.
> Update readme: added an example to Usage

- storage/gcloud/aio/storage/bucket.py
This is a solution for #140 
I know that the code in this PR is not as nice as the rest of the gcloud-aio repository, but I appreciate you encouraging my submission and having patience with a newbie. I value your feedback.
> feat(storage) add pagination to list_blobs()

- bigquery/gcloud/aio/bigquery/__init__.py
- bigquery/gcloud/aio/bigquery/bigquery.py
- bigquery/tests/integration/smoke_test.py
1) Make bigquery.Table.load method accept source format, autodetect & write disposition parameters
2) Add bigquery.Table.query method to create table from a query result
> Add parametrization to load job, add query method

- auth/gcloud/aio/auth/session.py
Related #126
@TheKevJames should I write some test with mocks or is it enough?
> add minor handling for status exceptions

- datastore/README.rst
> Update README.rst in datastore

- storage/gcloud/aio/storage/storage.py
- port `upload_from_filename` method to `gcloud-aio-storage`
- port `download_to_filename` method to `gcloud-aio-storage` [update]
> feat(gcloud-aio-storage): add upload_from_filename

- pubsub/setup.py
Major version bump for backwards incompatible change https://github.com/talkiq/gcloud-aio/pull/201.
> chore(pubsub): bump version

- pubsub/setup.py
Releasing fix PRs #216 and #217.
> chore(pubsub): bump pubsub 2.1.0 -> 2.1.1

- pubsub/gcloud/aio/pubsub/subscriber_client.py
If there are ways to test code under `if REST:` condition please let me know >.<
> hotfix(pubsub) Fix imports in subscriber_client.py

- pubsub/setup.py
Picking up fix to import error: https://github.com/talkiq/gcloud-aio/pull/219
> chore(pubsub): bump pubsub 2.1.1 -> 2.1.2

- bigquery/gcloud/aio/bigquery/__init__.py
- bigquery/gcloud/aio/bigquery/bigquery.py
bq_publisher uses some parameters that are not supported in bigquery atm.
> feat(bigquery) Add some of the missing params to insert_via_load

- bigquery/setup.py
Releases new feature https://github.com/talkiq/gcloud-aio/pull/231
> chore(bq): bump bigquery from 5.0.0 -> 5.1.0

- auth/setup.py
> chore(auth): bump to 3.4.4

- datastore/gcloud/aio/datastore/__init__.py
> fix(datastore): Expose MutationResult as datastore.MutationResult

- pubsub/README.rst
- pubsub/gcloud/aio/pubsub/__init__.py
- pubsub/gcloud/aio/pubsub/metrics_agent.py
- pubsub/gcloud/aio/pubsub/subscriber.py
- pubsub/gcloud/aio/pubsub/subscriber_message.py
- pubsub/noxfile.py
- pubsub/tests/unit/subscriber_test.py
The final PR for HTTP-bases subscriber.
This is an opportunity to take another look at the code, complete any hanging conversation and finally m e r g e.
I will also be testing this on staging and making sure performance is still ok.
tasks:
> feat(pubsub): subcribe()

- pubsub/gcloud/aio/pubsub/subscriber_client.py
sorry for unnecessary long rebase chain, but it's a lot more convenient this way
> feat(pubsub): list_subscriptions method

- pubsub/setup.py
Pulling in #271, #270, #265, and #243.
> chore(pubsub): bump to v4

- pubsub/setup.py
Releasing https://github.com/talkiq/gcloud-aio/pull/280
> chore(pubsub): bump to 4.0.2

- pubsub/gcloud/aio/pubsub/subscriber.py
This should make shutdown a little better on logging side
> chore(pubsub) Close subscriber session during shutdown

- pubsub/setup.py
> chore(pubsub): bump to 4.0.3

- pubsub/setup.py
Pulling in #264 (adds optional parameter to a constructor; minor bump) and #289 (adds internal changes for testing; micro bump) with a minor bump.
> chore(pubsub): bump to 4.2.0

- pubsub/setup.py
Pulls in https://github.com/talkiq/gcloud-aio/pull/293.
> chore(pubsub): bump to v4.3.0

- storage/gcloud/aio/storage/storage.py
Updated links for encoding URI paths.
> docs(storage): Updated links to encoding URI path.

- datastore/gcloud/aio/datastore/datastore.py
- datastore/tests/integration/smoke_test.py
- datastore/tests/unit/datastore_test.py
> feat(datastore) Support creating a mutation from Value objects

- taskqueue/gcloud/aio/taskqueue/queue.py
These methods were making use of the old Session.request() call rather
than Session.$method(), which enforces `timeout` usage compatible with
recent versions of `aiohttp`. Switching over should avoid any issues
running into AttributeErrors.
Fixes #346
> fix(taskqueue): use new Session APIs for pushqueues

- auth/setup.py
Bumping `setup.py` patch version to release #367 to public.
> chore(auth):  Bump patch version

- auth/requirements.txt
- bigquery/tests/integration/smoke_test.py
This is done in hopes to widen the compatibility within others' projects.
> Decrease the lower bound of compatible requests libs

- auth/setup.py
Patch version update to indicate the change represented by https://github.com/talkiq/gcloud-aio/pull/432
> Updates version to 3.7.1 for patch release

- auth/setup.py
> chore(auth): bump patch version

- .circleci/config.yml
- auth/gcloud/aio/auth/session.py
- auth/gcloud/aio/auth/token.py
- storage/gcloud/aio/storage/blob.py
- taskqueue/tests/integration/pushqueue_test.py
Python 3.12.0 is live, make sure we test on it!
> chore(ci): add py312 to matrix test targets

- storage/gcloud/aio/storage/blob.py
Propagate content type when uploading using a blob object.
> feat(storage): blob upload with content type

- .github/CODEOWNERS
> chore: Update CODEOWNERS with cphoward

- auth/pyproject.rest.toml
- auth/pyproject.toml
Our fstelephony service needs the fix of pull request #886 . Making a new release for 5.4.2.
> chore(release): bump version

- pubsub/gcloud/aio/pubsub/subscriber_client.py
- pubsub/pyproject.rest.toml
- pubsub/pyproject.toml
Include methods to work with snapshots in `gcloud-aio-pubsub`.
the methods included are:
- seek
- create_snapshot
- delete_snapshot
- list_snapshots
- get_snapshot
> feat(pubsub): add support for snapshots

- datastore/pyproject.rest.toml
- datastore/pyproject.toml
Include changes from https://github.com/talkiq/gcloud-aio/pull/913 and https://github.com/talkiq/gcloud-aio/pull/925
> chore(datastore): bump version to 9.1.0
