talkiq/gcloud-aio

auth/requirements.txt
auth/setup.py

Extracted from #13 -- we will need aiohttp v2 for cloudtasks v2beta2, and anyway v1 has been long-deprecated.

fix(auth): bump aiohttp dependency to latest major

---

taskqueue/gcloud/aio/taskqueue/taskmanager.py

this helps mitigate 'Broken Pipe' errors with long-running sessions against GCloud services which are less prone to supporting long-lived connects

enforce single session per every poll() and process()

---

auth/gcloud/aio/auth/auth.py

Removed the `assert self.project == self.service_data['project_id']`, since there's no reason why a service account must be used in the originating project.
Did a whole bunch of cleanup while I was here. Might be worth checking the diff at the commit level.

Auth allow cross project

---

pubsub/tests/integration/smoke_test.py
taskqueue/gcloud/aio/taskqueue/taskqueue.py
taskqueue/gcloud/aio/taskqueue/utils.py
taskqueue/requirements.txt
taskqueue/setup.py

The previous retry loop `await`ed the same coroutine multiple
times, which led to swallowing every exception with:
> RuntimeError: cannot reuse already awaited coroutine
This patchset uses `backoff` rather than rolling our own --
it should now capture the real exception in the worst case
and _actually retry failed requests_ in the standard case.

fix(taskqueue): fix retry handler for taskqueue requests

---

storage/gcloud/aio/storage/bucket.py
storage/gcloud/aio/storage/storage.py
storage/tests/integration/smoke_test.py

Added support for properly encoding Storage object names with special paths to follow https://cloud.google.com/storage/docs/json_api/#encoding

fix(encoding): fix URI path encoding for GCP REST API

---

auth/gcloud/aio/auth/auth.py
auth/requirements.test.txt
auth/tests/integration/smoke_test.py

Users can now authenticate through gcloud-aio-auth using default application credentials (`adc.json`)
Added a few cases to the auth tests.
Compatibility has been tested with: `gcloud-aio-bigquery`, `gcloud-aio-datastore`, and `gcloud-aio-taskqueue`

feat(auth): enable auth with default application credentials

---

datastore/gcloud/aio/datastore/datastore.py
datastore/tests/integration/smoke_test.py

When invoking a non-transactional commit, the `transaction` key can (and
should) be omitted. This change allows users to commit in
non-transactional mode without providing a transaction key (or arbitrary
string) by ensuring that key is optional.
This is a breaking change, since the `commit` API changed.

fix(datastore): allow non-transactional datastore usage w/o ID

---

datastore/README.rst
datastore/gcloud/aio/datastore/__init__.py
datastore/gcloud/aio/datastore/constants.py
datastore/gcloud/aio/datastore/datastore.py
datastore/gcloud/aio/datastore/filter.py
datastore/gcloud/aio/datastore/query.py
datastore/gcloud/aio/datastore/value.py
datastore/tests/integration/smoke_test.py
datastore/tests/unit/filter_test.py
datastore/tests/unit/query_test.py
datastore/tests/unit/value_test.py

Add support for non-GQL queries
I realized after rebasing that it would have been better to add commits to the previous code review and squash at the end, just before merging. Sorry about that. It's not obvious but I addressed your comments from #69 and added a smoke test and a documentation example for the queries.

feat(datastore) add non-GQL queries

---

datastore/gcloud/aio/datastore/value.py
datastore/tests/unit/value_test.py

Evaluate value to 'NULL_VALUE' only when it's None, all other
false-like values will be evaluated as is.

fix(datastore): Value.to_repr fix for False-like values

---

auth/gcloud/aio/auth/token.py

Use utcnow() so that timezone changes don't affect token refreshing

fix(auth): Use utcnow() instead of now() to avoid issues with timezone changes

---

storage/gcloud/aio/storage/storage.py

Possibility to provide Optional query parameters to Storage.upload
This will work for simple and resumable uploads.
For instance, optional parameters can be used to set predefined
ACL on the object, provide kmsKeyName etc.

feat(storage): optional query parameters support in "upload"

---

pubsub/gcloud/aio/pubsub/subscriber_client.py
pubsub/setup.py

- fix `kwargs` expansion (must use `**kwargs` not `*kwargs`)
- bump pubsub release to `1.0.1`
I believe due to broken tests this will require a manual merge by @TheKevJames

fix(pubsub): fix kwargs expansion syntax in create_subscription

---

datastore/gcloud/aio/datastore/__init__.py
datastore/gcloud/aio/datastore/constants.py
datastore/gcloud/aio/datastore/lat_lng.py
datastore/gcloud/aio/datastore/value.py
datastore/tests/integration/value_types_test.py
datastore/tests/unit/lat_lng_test.py
datastore/tests/unit/value_test.py

The Python3-only and async version of https://github.com/talkiq/gcloud-rest/pull/40 with @TheKevJames' comments addressed!

feat(datastore) Add support for geoPointValue

---

bigquery/gcloud/aio/bigquery/bigquery.py

When google receives a bigtable insert and something goes wrong, this is not reflected by the HTTP status. Instead, the response contains a report of what did and what didn't work.
Prior this change this report was silently ignored by `gcloud.aio.bigquery.Table.insert`, and there was no way to notice data problems.

Make sure bigquery inserts actually return a result

---

.pre-commit-config.yaml
auth/README.rst
auth/gcloud/aio/auth/iam.py
auth/gcloud/aio/auth/token.py
auth/noxfile.py
auth/tests/unit/token_test.py
bigquery/gcloud/aio/bigquery/bigquery.py
datastore/gcloud/aio/datastore/datastore.py
kms/gcloud/aio/kms/kms.py
storage/gcloud/aio/storage/blob.py
storage/gcloud/aio/storage/storage.py
taskqueue/gcloud/aio/taskqueue/queue.py

This PR allows `service_file` to be any `io.IOBase` instance, like `io.StringIO`. In general, it allows any object with a `read()` method, but I think it's best to keep the type declaration stricter. A file-like object should inherit from `io.IOBase` anyway. The README was updated to reflect this change.
Fixes #92

Allow service_file to be an io.IOBase instance

---

datastore/gcloud/aio/datastore/datastore_operation.py

Google documents export API responds with Operation object which should have 'done' key
but it's missing when export is still in process.

datastore export to storage fails with 'done' keyerror.

---

storage/gcloud/aio/storage/storage.py
storage/tests/integration/smoke_test.py

According to the GCP Storage API documentation, the copy operation can be achieved either by using the `copyTo` endpoint or the `rewriteTo` endpoint. Google recommends using `rewriteTo`, since `copyTo` simply uses a single call to the behaviour of `rewriteTo` whereas multiple may be needed for large files or other multi-part copy causes.
`rewriteTo` exposes a `done` field in the response payload; if this is false then the value of the `rewriteToken` field must be used in subsequent calls until the copy operation is completed.
https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite
Testing:
- Added an extra flow to the smoke test to (1) copy the originally uploaded object, (2) verify that its contents are expected, (3) delete it on cleanup, and (4) ensure the deletion was …

feat(storage): implement copy operation

---

datastore/gcloud/aio/datastore/value.py
datastore/tests/unit/value_test.py

Slice the date string to drop the nanoseconds and trailing 'Z'.

fix(datastore): allow microsecond resolution timestamp values

---

datastore/gcloud/aio/datastore/value.py
datastore/tests/unit/value_test.py

Fix for #150 - encode/decode base64 blob values

fix(datastore): use base64 representation for blobs (fixes #150)

---

datastore/gcloud/aio/datastore/query.py

The Datastore API treats `None` and `0` differently for `offset` and
`limit` and sets a default of `None` -- this changeset ensures we aren't
overriding their defaults and can support both values as intended.

fix(datastore): avoid mangling None queryvals

---

datastore/gcloud/aio/datastore/value.py
datastore/tests/unit/value_test.py

I found one more corner case: datetimes with second resolution.

fix(datastore): handle additional legacy date formats

---

pubsub/gcloud/aio/pubsub/subscriber_client.py

Using uvloop I was getting the following exception:
> RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
ERROR: Top-level exception occurred in callback while processing a message
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py", line 72, in _wrap_callback_errors
callback(message)
File "/usr/local/lib/python3.7/site-packages/gcloud/aio/pubsub/subscriber_client.py", line 100, in _callback_wrapper
self.loop.create_task(callback(message))
File "uvloop/loop.pyx", line 1396, in uvloop.loop.Loop.create_task
File "uvloop/loop.pyx", line 1255, in uvloop.loop.Loop.call_soon
File "uvloop/loop.pyx", line 678, in uvloop.loop.Loop._check_thread

Ensure callback is scheduled in a thread-safe manner

---

.circleci/config.yml
auth/requirements.txt

Fixes a problem that prevents projects using gcloud-aio-storage from deploying into Google Cloud Functions.
- common requirement in gcloud-aio + google cloud function is yarl (required by aiohttp)
- yarl received a breaking change a few days ago; pinning this version lets deployment succeed
- will get in touch w aiohttp and yarl projects about the breaking change

feat(gcloud-aio): pin yarl for google cloud function compat

---

.circleci/config.yml
README.rst
auth/requirements.txt

This reverts commit 099cb35ed1c074ac4b226ae73e923814ddc6c927.
We determined that the yarl incompatibility only affects Google Cloud Functions (GCF), and is known to be pinned there at 1.4.2 -- we recommend users who use GCF to pin according to their docs here: https://cloud.google.com/functions/docs/writing/specifying-dependencies-python

Revert "chore(deps): pin yarl for google cloud function compat (#185)"

---

auth/gcloud/aio/auth/session.py
auth/requirements.txt
auth/tests/integration/smoke_test.py

Fixes #57 and #188
```
fb41299 (Kevin James, 71 seconds ago)
chore(auth): bump minimum aiohttp
aiohttp v4.0 is gearing up to be hard to support if we also want to work 
with aiohttp <v3.3. Since 3.3 is now over two years old, I feel comfortable
deprecating it to avoid the future headaches and complexity.
Fixes #57
e03e021 (Kevin James, 2 minutes ago)
fix(auth): fixup minimum aiohttp deps
Fixes #188
```

chore(auth): bump minimum aiohttp compatibility

---

storage/setup.py

Bumping `gcloud-*-storage`: `5.5.4 -> 5.6.0`

chore(storage): bump version

---

pubsub/gcloud/aio/pubsub/__init__.py
pubsub/gcloud/aio/pubsub/subscriber_client.py
pubsub/gcloud/aio/pubsub/subscriber_message.py
pubsub/gcloud/aio/pubsub/utils.py
pubsub/tests/unit/subscription_test.py

Add a layer of indirection for Google's Message class (`google.cloud.pubsub_v1.subscriber.message.Message`) with (`gcloud.aio.pubsub.subscriber_message.Message`);
Provide our own FlowControl class
Try removing scheduler --
This allows us to change the implementation details of our Message without the user having to change their usage of it, so that migration to full gcloud-aio can proceed underneath.
FlowControl is just a named tuple, so implementing it here means the user can stop importing it from google-cloud.
Finally, the Scheduler argument doesn't really make sense if we're migrating to fully asyncio since it allows the user to submit a custom queue for retrieving messages -- something that really makes more sense in a multi-thread context.
Steps ...
• ✅ evaluate if this is ergonomic …

feat(gcloud-aio-pubsub): start migrate subscriber to aio, wrap Message, FlowControl, nix Scheduler

---

pubsub/README.rst
pubsub/gcloud/aio/pubsub/subscriber_client.py
pubsub/tests/unit/subscription_test.py

I noticed that our docs on the `SubscriberClient` and `FlowControl` were out of date with the version of `google-cloud-pubsub` we are now using. I updated them to reflect the state of internals of `google-cloud-pubsub==1.7.0` (the version we are on) after digging through its source.
In addition, I noticed that the examples use `f = FlowControl(); f.max_messages` and such types of property lookups which our version of `FlowControl` doesn't have so I updated it to make the docs easy to follow.

chore(pubsub): update docs and FlowControl

---

pubsub/setup.py

Bump `pubsub-2.0.0 -> pubsub-2.0.1` to pick up documentation updates and minor fixes outlined in https://github.com/talkiq/gcloud-aio/pull/209.

chore(pubsub): bump version

---

pubsub/README.rst
pubsub/gcloud/aio/pubsub/subscriber_client.py

Okayyy, so we need `gcloud-rest-pubsub`. If I got it right at the moment `aio` uses `google-cloud-pubsub` under the hood. In that case I don't see why we can't do the same for `rest`! This PR is exactly for that.
I tested this locally and it seems to be working.

chore(pubsub) Add rest variant of pubsub package that uses grpc package under the hood

---

pubsub/setup.py

Releases `SubscriberClient` for `gcloud-rest-pubsub`. (https://github.com/talkiq/gcloud-aio/pull/210)

chore(pubsub): bump pubsub from 2.0.1 to 2.1.0

---

pubsub/gcloud/aio/pubsub/subscriber_message.py
pubsub/tests/unit/subscription_test.py

The `from_google_cloud` factory method was pulled out of the `SubscriberMessage` inadvertently, and this change reintroduces it along with a unit test for regression detection.

fix(pubsub): reintroduce from_google_cloud to SubscriberMessage

---

pubsub/gcloud/aio/pubsub/subscriber_client.py
pubsub/gcloud/aio/pubsub/subscriber_message.py
pubsub/tests/unit/subscription_test.py

so @jonathan-johnston draw my attention to the fact that things like that:
```
if BUILD_GCLOUD_REST:
class SubscriberMessage:
def __init__(self, **kwargs: Any) -> None:
raise NotImplementedError('this class is only implemented in aio')
@staticmethod
def from_google_cloud(message: Any) -> 'SubscriberMessage':
raise NotImplementedError('this class is only implemented in aio')
```
Should probably not exist in a working `gcloud-rest-*` library.
In this PR:
1. Remove `if BUILD_GCLOUD_REST` and define `SubscriberMessage` for both `-aio-` and `-rest-` variants
2. Cast `Message` to `SubscriberMessage` in  `callback` provided to `SubscriberClient.subscribe` method

fix(pubsub) Cast Message to SubscriberMessage in a callback passed to subscribe()

---

bigquery/setup.py

Picks up #214 to allow arbitrary project selection for development.

chore(bq): bump bigquery 4.1.0 -> 4.1.1

---

pubsub/gcloud/aio/pubsub/subscriber_client.py
pubsub/gcloud/aio/pubsub/utils.py

Currently calling [sub_keepalive.cancel()](https://github.com/talkiq/gcloud-aio/blob/pubsub-2.1.2/pubsub/gcloud/aio/pubsub/subscriber_client.py#L181) on the `asyncio.Future` returned by the subscriber does not properly invoke the original `cancel` method of Google's `StreamingPullFuture`. This fact was due to modifying and wrapping the future with the intention of getting Pub/Sub to correctly run callbacks on the asyncio event loop.
After some investigation, it was discovered that wrapping the future was not needed, and in fact only running the callback via `asyncio.run_coroutine_threadsafe`, which was added _after_ these changes, is needed to have Pub/Sub and asyncio play nicely together.
Now, `cancel`ling the returned future invokes the behaviour …

feat(pubsub): proper subscriber cleanup

---

pubsub/setup.py

Major version bump for backwards incompatible change https://github.com/talkiq/gcloud-aio/pull/223.

chore(pubsub): bump pubsub 2.1.2 -> 3.0.0

---

bigquery/gcloud/aio/bigquery/__init__.py
bigquery/gcloud/aio/bigquery/bigquery.py

I don't like this PR. There is no reason `get_job` should be a method of `Table` class, yet there is no other place for it. Unless we want to redesign `gcloud-aio-bigquery` :(
Let me know what you think

feat(bq) Add method for v2/jobs/get

---

bigquery/setup.py

Create a release for https://github.com/talkiq/gcloud-aio/pull/224 which introduces the following changes:
- Introduce `SchemaUpdateOption` which can be used in `Table.insert_via_load` to (1) allow new fields to be added, and (2) allow relaxing `REQUIRED` fields to `NULLABLE` via the respective options (1) `ALLOW_FIELD_ADDITION` and (2) `ALLOW_FIELD_RELAXATION`
- Add option `ignore_unknown_values` to `Table.insert_via_load` which, when specified, ignores any values in a row that are not present in the table schema
- Introduce a `Job` class which replaces the JSON dictionary returned by the API and enables actions to be taken on the created job like `Job.get_job`, `Job.get_query_results`, and `Job.cancel`
These changes are more ergonomic but breaking and thus requires a major version bump. …

chore(bigquery): bump version from 4.1.1 -> 5.0.0

---

bigquery/gcloud/aio/bigquery/bigquery.py

Long time no see. Another service uses `JobConfiguration#dryRun` and `JobConfigurationQuery#useQueryCache` parameters. Both of them only make sense for query insert, thus only one method affected.

feat(bigquery) Add support for dryRun and useQueryCache parameters

---

.circleci/config.yml
bigquery/gcloud/aio/bigquery/bigquery.py

Here we go again. So turned out `insert_via_query` can be totally executed against `destinationTable: null`. That kind of defeats the purpose of having this method in the `Table` class. So in this PR we move the method to `Job` (making `job_id` optional along the way) and mark previous one as deprecated.

feat(bigquery) Move insert_via_query to Job class

---

datastore/gcloud/aio/datastore/array.py

Difficult to find a good name for that one.
I noticed that while looking at #242. Static checkers can help prevent this type of problem now.

fix(datastore): Explicitly ask for Values when creating an Array

---

datastore/gcloud/aio/datastore/datastore.py

The [docs](https://cloud.google.com/datastore/docs/reference/data/rest/v1/projects/commit#response-body) are misleading: the API can just not include 'indexUpdates' instead of setting the number to zero.

fix(datastore) Handle case where commit API doesn't return indexUpdates

---

pubsub/README.rst
pubsub/gcloud/aio/pubsub/__init__.py
pubsub/gcloud/aio/pubsub/subscriber_client.py
pubsub/gcloud/aio/pubsub/subscriber_message.py
pubsub/requirements.txt
pubsub/tests/unit/subscription_test.py

REST endpoints + grpc-free `SubscriberMessage`. 
`ack_callback` is here to let any message "producer" define how message can be acked by clients. There should be a name for this pattern, but I don't know it :(

feat(pubsub) Add rest endpoints to pull, ack and nack messages

---

auth/requirements.txt

Okay, so a few apps in our stack are emitting: `aiohttp 3.7.3 has requirement chardet<4.0,>=2.0, but you have chardet 4.0.0.`
We believe that this is all tracked down to `aiohttp` included in this repo -- version `3.0.4` is the final version of chardet in the 3.x.x major version.
Note that this pin would need manual removal if a later version of aiohttp requires chardet >= 4.0.0; I'm not 100% sure this is the best way to do this, but I figured we can talk about it in this PR.

feat(gcloud-aio): narrow pin for aiohttp + requirement chardet

---

pubsub/gcloud/aio/pubsub/subscriber.py
pubsub/tests/unit/subscriber_test.py

An attempt to gracefully shutdown subscriber. First we shutdown producers, making sure they pushed everything they already had downstream _and wait until consumers consume everything from the message queue_ (this makes consumer logic a lot easier). Then we shut down consumer. By this time we know that message queue is empty, so all we need to do is to exhaust semaphore and wait until ack/nack queues are empty. After that we're good to go.

feat(pubsub) Gracefully shutdown subscriber

---

pubsub/gcloud/aio/pubsub/subscriber.py
pubsub/tests/unit/subscriber_test.py

Well, this is a tricky bug. During graceful shutdown in consumer we can be sure that previous tasks were correctly scheduled, but not the last one. The last one is a total uncertainty: it could be  that it wasn't scheduled, or we could fail to attach a callback to it.
This is the best solution I could come up with: properly wait for previous tasks but just a little bit for the very last lock.

fix(pubsub) Fix a bug in consumer's graceful shutdown

---

pubsub/gcloud/aio/pubsub/subscriber.py
pubsub/gcloud/aio/pubsub/subscriber_client.py

So at the moment we use a default `10s` receive timeout for long-polling pull requests. It turned out it works horribly under low traffic.
What user sees: things not working
What monitoring shows: both `num_of_unacked_messages` and `oldest_unacked_message` would spike, then few messages would get into a deadletter topic.
What debugging showed: some messages simply never get processed by application
Mind that I'm talking about the queue which has several actively listening consumers.
What I think is happening. Producer workers would open long-polling connections, drop them after 10 seconds, then open a new set etc. When a message is finally published, pubsub server tries to evenly distribute them between open polling requests and a lot of them have no actual client connected. So after …

fix(pubsub) Increase long polling timeout to 30s

---

pubsub/gcloud/aio/pubsub/publisher_client.py

Adds some more methods to the `PublisherClient`. Method signatures analogous to those implemented for our [SubscriberClient](https://github.com/talkiq/gcloud-aio/blob/daed41cac123db134835329d9e7365f7b9ad8911/pubsub/gcloud/aio/pubsub/subscriber_client.py).

feat(pubsub): list, create, delete topics

---

pubsub/gcloud/aio/pubsub/subscriber_message.py
pubsub/tests/unit/subscription_test.py

Just like `attributes` key, `data` can also be missing.

fix(pubsub) account for missing data key in SubscriberMessage

---

pubsub/gcloud/aio/pubsub/subscriber_message.py
pubsub/tests/unit/subscription_test.py

The `delivery_attempt` attribute is used with deadlettering and comes standard with the grpc python subscriber client. When a subscription is enabled with deadlettering, this attribute will be an integer. If it is not, it will default to `None` (same behavior as the grpc clients).
Note also the direct http responses to subscription pull requests:
Deadlettering enabled
```
{
"receivedMessages": [
{
"ackId": "<trimmed>",
"message": {
"data": "<b64encoded>",
"messageId": "1961954308846553",
"publishTime": "2021-01-28T20:32:34.033Z"
},
"deliveryAttempt": 1
}
]
}
```
Deadlettering not enabled (note deliveryAttempt is absent, despite [docs](https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions/pull#receivedmessage) saying it will be 0)
```
{
"receivedMessages": [
{ …
```

feat(pubsub): retrieve deliveryAttempt on subscriber pull

---

pubsub/gcloud/aio/pubsub/subscriber.py
pubsub/tests/unit/subscriber_test.py

Context: VAE-2332
tl;dr There are cases when  a certain `ack_id` cannot be acked no matter what. In that case whole batch will be contaminated and won't be able to get through. The best we can do if we encounter such error is to drop the batch and schedule individual ack requests for each `ack_id`.

fix(pubsub) Drop whole batch if (n)ack request throws 400

---

pubsub/gcloud/aio/pubsub/subscriber.py
pubsub/tests/unit/subscriber_test.py

When we do a final sendout, invalid messages raise and thus flood sentry with non actionable errors

chore(pubsub) Log ack/nack last call attempt in case of exception

---

pubsub/setup.py

Pulling in https://github.com/talkiq/gcloud-aio/pull/304 with a micro version bump (internal changes only).

chore(pubsub): bump pubsub to 4.3.3

---

pubsub/gcloud/aio/pubsub/subscriber_client.py

gcloud.aio.pubsub.subscriber_client.pull throws a key error when the request times out. This can occur if there are no messages in the subscription. I added a simple fix to default to an empty list when no messages are received. It may be a good idea to add better timeout handling at some point.
```
36 passed, 5 warnings in 2.42s
Name                                      Stmts   Miss  Cover   Missing
-----------------------------------------------------------------------
gcloud/aio/pubsub/__init__.py                11      0   100%
gcloud/aio/pubsub/metrics_agent.py            5      0   100%
gcloud/aio/pubsub/publisher_client.py        82     45    45%   18, 32-33, 42-43, 48, 52, 56, 59-67, 81-87, 98-104, 114-117, 123-138, 141, 144, 147
gcloud/aio/pubsub/subscriber.py             185 …
```

fix(pubsub): fixed subscriber pull timeout key error

---

auth/gcloud/aio/auth/session.py

Add `patch` to `BaseSession`, `AioSession` and `SyncSession`.
• this is a pre-requisite to individually modifying metadata for Google Storage objects, but def belongs in the auth module, as it's probably general enough that we'll figure a need for it elsewhere.
Unblocks:
• https://github.com/talkiq/gcloud-aio/pull/310

feat(auth): add http PATCH to BaseSession, AioSession, and SyncSession

---

.circleci/config.yml
.pre-commit-config.yaml
storage/README.rst
storage/gcloud/aio/storage/storage.py
storage/requirements.txt

- Adds `aiofiles` dependency to `aio.storage.storage` package
- Updates the doc references to builtin [open](https://docs.python.org/3/library/functions.html#open) to [aiofiles](https://github.com/Tinche/aiofiles)
- Bumps mypy due to https://github.com/python/mypy/issues/9739
- Improves `aio.storage.storage.Storage.download_to_filename` to use [aiofiles](https://github.com/Tinche/aiofiles) 
- Improves `aio.storage.storage.Storage.upload_from_filename` to use [aiofiles](https://github.com/Tinche/aiofiles)
@TheKevJames 
Moved from initial PR #309

Use non blocking aiofiles.

---

storage/gcloud/aio/storage/storage.py

Summary:
• adds a method `Storage.patch_metadata()` that accepts an arbitrary dictionary to patch stored object metadata
Related:
• https://switchcomm.atlassian.net/browse/VAE-2317
• ✅ https://github.com/talkiq/gcloud-aio/pull/311 — move Session.patch() to gcloud-(aio|rest)-auth
Testing:
• ✅ tested locally w `pip install -e ./storage`

feat(storage): add ability to make patch request to stored objects (metadata)

---

storage/gcloud/aio/storage/__init__.py
storage/gcloud/aio/storage/storage.py
storage/tests/integration/download_stream_test.py

Hi @TheKevJames & company,
I was taking a look at how I might get downloads from your library without downloading object contents into memory. I found some [documentation](https://docs.aiohttp.org/en/stable/client_quickstart.html#streaming-response-content) for aiohttp which recommended using the response.content attribute directly, instead of the response.read() method, for downloads of significant size. Since a lot of GCS objects are pretty big, I think this change is useful.
It doesn't modify the original `download` behavior, since it is a breaking change. Instead, this PR:
- adds a new method, `get_content`. This is just a clone of the download method, but with a `get_content` flag set when calling the private implementation
- changes the private implementation `_download` method to …

Add a function to get a streamed response

---

bigquery/gcloud/aio/bigquery/bigquery.py

Currently it is impossible for the user to paginate query results. Allowing one to pass through arbitrary query parameters will enable them to do so (see the full list here: https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/getQueryResults)
Example use case:
```python
params = {'maxResults': 100}
results = await job.get_query_results(params=params)
rows = results['rows']
page_token = results.get('pageToken')
while page_token:
params['pageToken'] = page_token
results = await job.get_query_results(params=params)
page_token = results.get('pageToken')
rows.extend(results['rows'])
```
Optionally, we can add additional behavior to do the pagination for them, either aggregating over all results, or perhaps more ideally allowing direct iteration over a specified `maxResults`.

feat(bigquery): accept request params

---

pubsub/gcloud/aio/pubsub/subscriber_client.py

I noticed there was no context manager protocol implemented in `SubscriberClient`. I might misunderstand the class, but this will allow the use of `async with` without relying on the following idiom:
```python
async with aiohttp.ClientSession() as session:
subscriber_client = SubscriberClient(session=session)
```
Instead, we will be able to do:
```python
async with SubscriberClient() as client:
....
```

feat(pubsub): Supporting context management protocol in SubscriberClient

---

.pre-commit-config.yaml
storage/gcloud/aio/storage/blob.py
storage/requirements.txt
storage/tests/integration/signed_url_test.py

The previous implementation via the iamcredentials API seems to no longer
be working. Signing the blob via standard PEM->PKCS methods seems to work
just fine, fortunately!
Basically, rather than offloading the signing work, we just do this 
locally, so this should be a performance improvement as well. Since our 
previous implementation only worked for SERVICE_ACCOUNT tokens *anyway*
(due to a mistake -- theoretically, we could have pulled the email from the
metadata server for GCE_METADATA tokens...), this shouldn't break backwards
compatibility.
Note that at the same time as the iamcredentials API breaking, it seems the
canonical uri for blob signs also was updated (the bucket name is now
included in the host instead of as part of the path). I suspect the two are
related.

fix(storage): fixup blob signing

---

datastore/gcloud/aio/datastore/query.py
datastore/tests/unit/query_test.py

Have Query.from_repr accept a list with a single dict in it as the format for the 'kind' key, the same as is produced by Query.to_repr.

Have Query from_repr support the 'kind' format generated by to_repr

---

.pre-commit-config.yaml

This one had to be manual since pylint has changed its tagging strategy
in such a way that renovate cannot detect. Future updates should be
automated as per usual.

chore(deps): bump dependency pylint to v2.8.2

---

storage/gcloud/aio/storage/storage.py

When uploading large files the current implementation uses a lot of memory without good reason, there is no need to read the complete file when upload can work with the file stream itself.

Do a buffered read when uploading local file instead of a full read.

---

auth/gcloud/aio/auth/session.py
auth/tests/unit/sessions_test.py

Related to https://github.com/talkiq/gcloud-aio/pull/324.
This change resolves the context manager bug detailed in the linked PR.

bug(auth): Prevent closing shared sessions from AIO/REST Sessions

---

auth/MANIFEST.in
bigquery/MANIFEST.in
datastore/MANIFEST.in
kms/MANIFEST.in
pubsub/MANIFEST.in
storage/MANIFEST.in
taskqueue/MANIFEST.in

We've been writing type hints but not even exposing them! (Relates to https://github.com/talkiq/gcloud-aio/issues/212)
When we run `mypy` via `pre-commit` we use `--ignore-missing-imports`, which suppresses this kind of error message:
```
error: Skipping analyzing "voiceai.gcloud.aio.pubsub": found module but no type hints or library stubs
```
In cases where no type hints are found, the assumed return value of any function in the library is `Any`. Since we are enforcing type hinting on our team we might as well use them and let our code use their type hints. In order to expose these type hints to the users of the package you have to follow PEP 561 (Distributing and Packaging Type Information):
> Package maintainers who wish to support type checking of their code MUST add a marker file …

feat(typing): expose type hints as per pep 561

---

pubsub/gcloud/aio/pubsub/subscriber.py
pubsub/tests/unit/subscriber_test.py

Each read of the deadline counts towards the GCP Admin Operations
quota, which has a hard limit of 6000 ops/min at the time of writing.
This can causes unexpected quota overages if there are many services
making use of the subscriber.
This change disables the ack deadline cache refresh behavior by
default, and users must now opt-in to enable it.

feat(pubsub): no ack deadline cache refresh by default

---

storage/gcloud/aio/storage/storage.py
storage/tests/integration/metadata_test.py

Since gcloud supports a data body in its rewrite method, the copy
funcion can expose this to its public endpoint. This also enables the
enduser to set other metadata for the copied object.
https://github.com/talkiq/gcloud-aio/issues/362

feat(storage): Add data to copy endpoint.

---

kms/README.rst
kms/gcloud/aio/kms/utils.py

BREAKING CHANGE: avoid calling `.decode()` on the resulting payload of
`decode()` to account for non-utf-8 encodings and other user behaviour;
clients should know what data type they're expecting here and act
accordingly.

feat(kms): do not convert decode() result to str

---

datastore/tests/unit/value_test.py
pubsub/gcloud/aio/pubsub/subscriber.py
pubsub/tests/unit/subscriber_test.py
pubsub/tests/unit/subscription_test.py

Bit of a grab bag PR, happy to split apart if there's any confusion in reviewing. Basically, this is the result of seeing a bunch of warnings in our test output and cleaning them out one-by-one in case there were any "real" issues here. Turns out, all issues were on the test side of things; eg. invalid tests, or testing behaviour in an incorrect fashion, or not cleaning up after themselves.
* `test_to_repr_with_blob_value` wasn't being collected
* `test_importable` was a noop
* `test_construct_subscriber_client` instantiated a client outside of an
async context
* the coverage.py reporter for the pubsub subscriber choked on some
syntax issues in py2 which wouldn't have been accessible at runtime
* several pubsub tests did not correctly cleanup after themselves and
threw odd asyncio …

chore(tests): fixup some invalid tests

---

storage/gcloud/aio/storage/blob.py
storage/gcloud/aio/storage/constants.py
storage/gcloud/aio/storage/storage.py

Ended up almost breaking prod when switching to this due to the low default timeout, which is hidden when using Blob.download. Here is a PR to add this parameter.
Not sure what the 'no name storage' in your test suite is about.

add timeout parameter to blob download

---

storage/gcloud/aio/storage/storage.py

Object name encoding fix: for any other methods, object name encoding is perfomed, but not for the Storage().patch_metadata() method

fix(storage): Object name for patch_metadata

---

pubsub/gcloud/aio/pubsub/subscriber.py

Graceful worker cancellations during subscriber shutdown should not be cause for alarm or logged at the error level. Additionally, it can be useful to track these separately, as cancellations and true worker errors are different issues.

fix(pubsub): gracefully handle worker cancellations

---

pubsub/setup.py

It's been a long time since the last release but there have been more changes than was expected in the previous patch version bump. Fortunately no release was made on the patch version but one will be made on this minor version. The changes include:
* gracefully handle worker cancellations: https://github.com/talkiq/gcloud-aio/pull/401
* fixup some invalid tests: https://github.com/talkiq/gcloud-aio/pull/387
* no ack deadline cache refresh by default: https://github.com/talkiq/gcloud-aio/pull/370
* expose type hints: https://github.com/talkiq/gcloud-aio/pull/368
* add custom retry policy example: https://github.com/talkiq/gcloud-aio/commit/860c8e05de0c69e5f254357e267e785ab221f5e6#diff-92d64c121276956e129d509ac699180f8c32c6e03f6c49e75e8cc35f6be6096f
* fixup type hint in `PubsubMessage`: …

chore(release): bump pubsub minor version

---

pubsub/README.rst

Missing link from the section on `Customization`:
```
As such, we recommend configuring your own policies on an as-needed basis. The
`backoff`_ library can make this quite straightforward! For example, you may
find it useful to configure something like:
```

docs(pubsub): add missing backoff lib link

---

storage/gcloud/aio/storage/bucket.py

Just a minor feature that lets the user provide timeout to `get_blob`.

Allow timeout in get_blob in storage

---

auth/gcloud/aio/auth/session.py

The PR removes explicit wrapping of the passed timeout into `aihttp.ClientTimeout` (aiohttp does wrapping on its own if needed), allowing to pass `aihttp.ClientTimeout` instance as `timeout` as well as any `float`. This gives users more control over timeouts.

Allow timeout for AioSession to be ClientTimeout

---

auth/gcloud/aio/auth/session.py

When sending requests, `aiohttp` intelligently converts timeout values from floats and ints into `ClientTimeout` but also accepts `ClientTimeout` (https://github.com/aio-libs/aiohttp/blob/v3.8.1/aiohttp/client.py#L440). Unfortunately, the `ClientSession` constructor is not so helpful and only accepts `ClientTimeout` values (https://github.com/aio-libs/aiohttp/blob/v3.8.1/aiohttp/client.py#L277).
Therefore when constructing the `ClientSession` object we must convert the `self._timeout` member variable to a `ClientTimeout` object before passing it in.

fix(auth): coerce timeout to clienttimeout for clientsession

---

storage/gcloud/aio/storage/storage.py

Warp data in io.BytesIO when posting to ensure aiohttp do not use BytesPaylood. Fixes #404.
Not sure how to write a test for that, since it would require a >1MB data payload to trigger the warning...

fix(storage): fix warning uploading multipart data

---

datastore/gcloud/aio/datastore/__init__.py
datastore/gcloud/aio/datastore/query.py
datastore/tests/integration/smoke_test.py
datastore/tests/unit/gql_query_test.py

According to the [GQL Reference](https://cloud.google.com/datastore/docs/reference/gql_reference#clauses), cursors are available on the `LIMIT` and `OFFSET` clauses of GQL queries.
This PR gives support for using cursors as binding parameters of GQL queries. A parameter on a GQL query can either be a value of different types (already implemented) or a cursor (implemented on this PR). Check the syntax [here](https://cloud.google.com/datastore/docs/reference/data/rest/v1/projects/runQuery#gqlqueryparameter).

feat(datastore): add support for cursors on GQL queries

---

pubsub/gcloud/aio/pubsub/subscriber.py

In python3.8 CancelledError was changed to be a subclass of BaseException
This makes sure to catch CancelledError so that it will trigger the shutdown behavior on the subscriber

fix: Subscriber shutdown exception handling fix

---

bigquery/gcloud/aio/bigquery/__init__.py
bigquery/gcloud/aio/bigquery/utils.py
bigquery/tests/unit/utils_test.py

Convenience method so client libs don't need to do the converting
themselves to get a slightly more useable dictionary format from their
BQ responses.

feat(bigquery): convert responses to dicts

---

.circleci/config.yml

Poetry can't be installed in python 3.6. Rather than making that a
special case, use the nox image for everything.

fix(ci): use nox image for everything

---

.pre-commit-config.yaml
auth/gcloud/aio/auth/session.py
pubsub/gcloud/aio/pubsub/subscriber.py
pubsub/tests/unit/subscriber_test.py

Enable cyclomatic complexity plugin, which uses the McCabe Cyclomatic complexity to define how complex a function is. By default the maximum cyclomatic complexity is `10`.
[Cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) is the number of linearly independent paths within it, or in layman's terms: how many paths can be taken "through the code". A cyclomatic complexity of `10` means there's 10 linearly independent paths to exit a function.
And a bonus: pin importlib<5.0 in order to fix a recent flake8 dependency issue.

chore(lint): enable mccabe complexity plugin with default settings

---

pubsub/gcloud/aio/pubsub/subscriber.py
pubsub/tests/unit/subscriber_test.py

Main goal: ensure that `hash(message)` is useful: eg. that log messages
can be relied on to be constant for cases where it is "the same error"
and different for cases where it is not. This allows for clients to do
things such as alert when the rate of a given error message is above a
given threshold.
While I was here, I cleaned up the other log strings in the file to make
'em all consistently typed/formatted/etc.

chore(pubsub): clean up log messages

---

storage/gcloud/aio/storage/storage.py
storage/tests/unit/upload_retry_test.py

The retry mechanism in storage._do_upload() is broken because when you
perform a request on a stream in aiohttp, the stream is automatically
closed. Therefore, the retry raises an error: I/O Operation on closed
file.
This fix monkeypatch the close function on the stream to ensure
it remains open until all retries are performed.

fix(storage): upload retry results in IO error

---

bigquery/gcloud/aio/bigquery/bigquery.py
bigquery/gcloud/aio/bigquery/dataset.py
bigquery/gcloud/aio/bigquery/job.py
bigquery/gcloud/aio/bigquery/table.py
datastore/gcloud/aio/datastore/datastore.py
docs/aio.md
docs/gcloud.md
docs/rest.md
kms/gcloud/aio/kms/kms.py
pubsub/gcloud/aio/pubsub/publisher_client.py
pubsub/gcloud/aio/pubsub/subscriber_client.py
storage/gcloud/aio/storage/storage.py
storage/tests/unit/upload_retry_test.py
taskqueue/gcloud/aio/taskqueue/queue.py

Solves a couple related goals in a consistent way across all projects:
* allows users to provide an api host via code instead of only via env
var
* load that value at time of constructing the client rather than import
time
Thanks to @josipbudzaki in #542 and @adriangb in #539 for providing a
baseline approach.
Fixes #202.

feat: load emulator hosts at runtime

---

auth/gcloud/aio/auth/session.py
auth/pyproject.rest.toml
auth/pyproject.toml

Python 3.11 seems to raise a bunch of warnings as errors that were previously being suppressed such as this one:
```
/usr/local/lib/python3.11/site-packages/gcloud/aio/auth/session.py:121: in session
connector = aiohttp.TCPConnector(verify_ssl=self._ssl)
/usr/local/lib/python3.11/site-packages/aiohttp/connector.py:776: in __init__
self._ssl = _merge_ssl_params(ssl, verify_ssl, ssl_context, fingerprint)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ssl = None, verify_ssl = False, ssl_context = None, fingerprint = None
def _merge_ssl_params(
ssl: Union["SSLContext", bool, Fingerprint, None],
verify_ssl: Optional[bool],
ssl_context: Optional["SSLContext"],
fingerprint: Optional[bytes],
) -> Union["SSLContext", bool, Fingerprint, None]:
if verify_ssl …
```

fix(DeprecationWarning): thrown by aiohttp in python3.11

---

.circleci/config.yml

Since our `gcloud-aio-*` are considered PyPI critical packages, we need
to switch the way we publish them to use a PyPI token instead of
username and password.
We're adding the names of the environment variables to the matrix that's
used to create the CircleCI jobs and removing the usage of `--username`
and `--password` in `poetry publish`, preferring to set the
environemnt variable `POETRY_PYPI_TOKEN_PYPI` instead. See
[here](https://python-poetry.org/docs/repositories/#publishable-repositories)
for more information.
This change requires setting the following environment variables:
```
- POETRY_PYPI_TOKEN_PYPI_AUTH
- POETRY_PYPI_TOKEN_PYPI_BIGQUERY
- POETRY_PYPI_TOKEN_PYPI_DATASTORE
- POETRY_PYPI_TOKEN_PYPI_KMS
- POETRY_PYPI_TOKEN_PYPI_PUBSUB
- POETRY_PYPI_TOKEN_PYPI_STORAGE
- …
```

chore(poetry-publish): use pypi-token env variable for `poetry publish`

---

auth/pyproject.rest.toml
auth/pyproject.toml

We're bumping the version number from 4.1.3 to 4.1.4 without any changes since the 4.1.3 deploy is borked in CircleCI.

feat: bump version for gcloud-*-auth to 4.1.4

---

.circleci/config.yml

`echo 'export POETRY_PYPI_TOKEN_PYPI="$token"' >> "$BASH_ENV"` interpolation doesn't work, cahnging this to `echo 'export POETRY_PYPI_TOKEN_PYPI=$token' >> "$BASH_ENV"` seems to do the trick.

fix(circleci): bad interpolation when creating PYPI_TOKEN_*

---

.circleci/config.yml

Turns out that doing `echo '$asd'` with single quotes prints `asd`, whereas using `echo "$asd"` will interpolate the value of `asd` and thus print the value within the variable. We're currently using single quotes instead of double quotes, so we gotta make them single quotes double quotes for that sweet interpolation to work.

fix: bad interpolation of token in BASH_ENV

---

auth/pyproject.rest.toml
auth/pyproject.toml

Need to re-release `gcloud-*-auth` to properly publish to PyPI since the deployment is borked due to PyPI requiring us to use tokens instead of username and password in order to release.

feat(auth): bump `gcloud-*-auth` to 4.1.5 in order to re-release

---

.circleci/config.yml

Use repo-local secrets for PyPI publishing. Progress towards unblocking
external contributors for running tests with secrets (eg. to access
google APIs).
Blocked on talkiq/terraform#1977

feat(ci): use repo-local secrets

---

pubsub/gcloud/aio/pubsub/subscriber.py

Improve some logging:
* move some info logs to debug, as they're generally just noise for most
users
* avoid logging requested shutdowns as warnings, and log unexpected ones
as errors

feat(pubsub): improve logging

---

pubsub/gcloud/aio/pubsub/subscriber_client.py

These are just convenience methods, no reason to only have them on the
PublisherClient.

feat(pubsub): add topic/sub convenience methods to SubscriberClient

---

auth/gcloud/aio/auth/token.py

If `self.acquire_access_token()` fails for any reason other than task
cancellation, we currently never detect it and will repeatedly raise
the exception upon waiting for the token.
See https://github.com/talkiq/gcloud-aio/pull/500 for further details of
where this issue was first surfaced but only partially fixed.

fix(auth): reset token acquisition future after failure

---

auth/pyproject.toml

Bumping auth to include patch: https://github.com/talkiq/gcloud-aio/pull/628

chore(release): bump auth version

---

storage/poetry.lock
storage/pyproject.toml

I only bump the `storage` version to 8.3.0 in pyproject.toml.
The correct way to do this should be to create an `alpha` version from my branch (not from `master` as I did). After testing it, merge my branch to `master` and create the `minor` tag/release.
In this particular case, I've already merged my branch to master and create the `alpha` version from `master`. Thus, the only thing left to do is to change the pyproject.toml version.
If you want to see what I added to `master` at that time, please [see this link](https://github.com/talkiq/gcloud-aio/commit/d68dcbf62fea7125fc11044142e85a32dc04a999)

bump(storage-8.3.0): from 8.2.1a0 to 8.3.0

---

storage/gcloud/aio/storage/bucket.py

Add the `match_glob` parameter to `Bucket.list_blobs` in order to use the `matchGlob` parameter available in the [API](https://cloud.google.com/storage/docs/json_api/v1/objects/list#parameters).
This is required to implement [this PR](https://github.com/apache/airflow/issues/32650) on the Airflow repository

Add match_glob param to list_blobs

---

storage/gcloud/aio/storage/__init__.py
storage/gcloud/aio/storage/storage.py

In order for this library to be compatible with the official python Google Cloud Storage library, it needs to accept the same value for configuring the `STORAGE_EMULATOR_HOST` environment variable. This will allow users to rely on both libraries in a single project.
Fixes: https://github.com/talkiq/gcloud-aio/issues/631

Accept the official format for `STORAGE_EMULATOR_HOST` env var

---

auth/gcloud/aio/auth/token.py

Perf optimization: for GCE_METADATA tokens, there's no hit the token refresh
endpoint when we're only looking to call `get_project()` and have the value set
locally.

perf(auth): avoid unnecessary token refresh on get_project()

---

auth/gcloud/aio/auth/session.py
auth/pyproject.rest.toml
auth/pyproject.toml
bigquery/tests/integration/smoke_test.py

* Pull in perf change: https://github.com/talkiq/gcloud-aio/pull/653
* Fix `ssl` flag for `gcloud-aio-auth`
* Fix flaky BQ integration tests with `backoff`

fix(auth): correctly set ssl flag for aio

---

storage/gcloud/aio/storage/blob.py
storage/pyproject.toml
storage/tests/integration/signed_url_test.py

This PR aims to solve the issues explained in https://github.com/talkiq/gcloud-aio/pull/323#issuecomment-1900605859.
To summarize, this PR re-adds support for using the IAM API to sign blobs in case there is no service account private key available locally.

fix(storage): Restore option to sign blob urls by using the signBlob endpoint of the IAM API

---

auth/gcloud/aio/auth/token.py

Since this lib uses `aiohttp` for aio calls and `requests` for rest calls, we need to suppport both usages.
For getting iap token I use the same solution as in lines 200-203.

fix(rest-auth): resp.text() for aiohttp but resp.text for requests lib

---

.pre-commit-config.yaml
auth/gcloud/aio/auth/session.py
storage/gcloud/aio/storage/blob.py
storage/gcloud/aio/storage/storage.py
storage/poetry.lock
storage/poetry.rest.lock
storage/pyproject.rest.toml
storage/pyproject.toml
storage/tests/integration/smoke_test.py

Subset of #698, split to let me release `auth` before `storage`.
Modified to fixup some type hint issues and an issue with header casing.
Fixes #45

feat(storage): support gzipping files before uploading them

---

datastore/gcloud/aio/datastore/__init__.py
datastore/gcloud/aio/datastore/constants.py
datastore/gcloud/aio/datastore/filter.py
datastore/tests/integration/smoke_test.py

Add support for "IN" filter so that Firestore in Datastore mode would be able to execute single query with IN filter instead of multiple parallel queries.

feat(datastore): Support "IN" query filter

---

auth/gcloud/aio/auth/token.py
auth/pyproject.toml

Some of the GCP products when retrieving the JWT token from the GCE
Metadata Server come with the `email` claim, but some have recently
started not returning that claim as part of the JWT payload. Adding the
`format=full` query parameter to the GCE Metdata Server API seems to
return the `email` claim for these cases, along with other GCE Metadata
which for the time being we do not need and thus, we discard.
[See these docs for more
information.](https://cloud.google.com/compute/docs/instances/verifying-instance-identity#request_signature)

fix(auth): use the full format for the JWT payload in IAPToken

---

datastore/gcloud/aio/datastore/filter.py
datastore/tests/unit/filter_test.py

This PR adds support to IN filters with plain old list such as
`query.filter('names IN', ['aaa', 'bbb'])`

feat(datastore): Support plain old list arg with IN filter

---

pubsub/gcloud/aio/pubsub/subscriber.py

Clean up our general approach to logging:
* include an `exc_message` extra wherever an exception is relevant to
the log, to allow for message-level aggregation (eg. grouping errors
by raised exception)
* avoid using string templates in exception messages, to make
aggregation easier (`message` is always a constant string for any
given error case, so it can be alerted on)
* downgrade application callback exceptions to a warning, since that can
be a normal part of user flows -- if users want it logged at the error
level, they can always do that themselves, we shouldn't be enforcing
it

feat(pubsub): clean up logging

---

storage/gcloud/aio/storage/blob.py

Issue: When using `blob.get_signed_url` without passing a `session` or `iam_client`, a new session will be opened but never closed.
Summary of changes: Check if the user provided a session either through `session` or implicitly through `iam_client`, and if not close the `iam_client` after the operation.

fix(storage)/get-signed-url-unclosed-session

---

auth/gcloud/aio/auth/token.py
auth/tests/unit/token_test.py
bin/build-rest

If acquire_access_token exhausts retries (for any crazy reason), we continue to try to call it over and over again. This happens pretty infrequently but there's no way to fix it when it does happen.

fix(storage): BaseToken.ensure_token should not cache failed calls to acquire_access_token

---

storage/gcloud/aio/storage/storage.py
storage/pyproject.rest.toml
storage/pyproject.toml
storage/tests/integration/compose_test.py

This PR implements support for basic object composition operations in GCS (see <https://cloud.google.com/storage/docs/composing-objects>) by adding a new method `compose` to `gcloud.aio.storage.Storage`. I say "basic" here, because this implementation currently doesn't support some of the more advanced query parameters, e.g. `ifGenerationMatch`, which can be used to halt a compose operation if certain preconditions about the constituent blobs aren't met. More information about these query parameters can be found here: <https://cloud.google.com/storage/docs/json_api/v1/objects/compose>. That said, the new method appears to work for these more basic cases, and provides a foundation to add more functionality onto later.

feat(storage): implement compose method

---

.circleci/config.yml

Buster (Debian 10) reached EOL

chore(ci): use debian:bullseye-slim executor for github job

---

datastore/pyproject.rest.toml
datastore/pyproject.toml

Given the changes in https://github.com/talkiq/gcloud-aio/pull/922, we need to release a new major version of datastore.
The result of `runQuery` has a breaking change

chore(datastore): bump version

---

.github/renovate.json5

I overhauled my shared renovate configs to make things a bunch more granular
(https://github.com/TheKevJames/tools/commit/0f05ec1246df62f732382648b00ee122fe57b611 ).
This commit migrates our changes in-place to follow the new schema. Should be a
noop!

refactor(renovate): clean up renovate config
